name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # You can specify multiple versions if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate .env file from secrets
      run: |
        echo "PG_SSL_REQUIRED=true" >> .env
        echo "PORT=8080" >> .env
        echo "JWT_SECRET=secret" >> .env
        echo "JWT_SKIP_AUTH=false" >> .env
        echo "PG_STRING=${{ secrets.PG_STRING }}" >> .env

    - name: Print .env file (Debugging Step)
      run: cat .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Start the project
      run: npm start &
      timeout-minutes: 1
